name: Docker

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    name: Docker
    uses: molssi-seamm/devops/.github/workflows/Docker.yaml@main
    with:
      image : molssi-seamm/seamm-psi4
      description: An Psi4 executable packaged for use with SEAMM or standalone
    secrets: inherit
